### ISSUE TITLE
Not compatible with Redmine 2.2.3

### ISSUE THREAD

**Issue by ks780** [anjlab/redmine_inline_note_images_plugin#10]
im sorry but i dont know ruby, i just wanted to install under turnkey redmine vm, but your plugin did not worked well for me, i was able to view some issues but most of them were giving me errors and here is the production log about one of them

i hope this helps to solve it

![redmine2 2 3](https://f.cloud.github.com/assets/2713970/203484/ef394fa8-8138-11e2-96dd-dfb94e02e1c2.png)

Started GET "/issues/7" for 192.168.1.100 at Tue Feb 26 18:44:38 +0200 2013
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"7"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (8.3ms)
  Rendered issue_relations/_form.html.erb (2.9ms)
  Rendered issues/_relations.html.erb (5.6ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (1.8ms)
  Rendered issues/_history.html.erb (17.6ms)
  Rendered issues/show.html.erb within layouts/base (66.2ms)
Completed 500 Internal Server Error in 167ms

ActionView::Template::Error (compile error
/var/www/redmine/plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb:2: syntax error, unexpected ':', expecting ')'
');   journal.details.where(property: 'attachment').each do |a| 
                                     ^
/var/www/redmine/plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb:2: syntax error, unexpected ')', expecting kEND
');   journal.details.where(property: 'attachment').each do |a| 
                                                   ^):
    1: <div class="attachments" style="margin-bottom: 16px;">
    2:   <% journal.details.where(property: 'attachment').each do |a| %>
    3: 
    4:       <% attachment = Attachment.find_by_id a.prop_key %>
    5:       <% if attachment.present? && attachment.image? %>
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in`view_issues_history_journal_bottom'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_history.html.erb:19:in`_app_views_issues__history_html_erb___641410495_110370350'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in`_app_views_issues__history_html_erb___641410495_110370350'
  app/views/issues/show.html.erb:124:in `_app_views_issues_show_html_erb___401764792_111250730'
  app/controllers/issues_controller.rb:119:in`show'
  app/controllers/issues_controller.rb:116:in `show'

**Comment by vdostman** [comment]
Same issue here. Please let me know if you find a solution.

Started GET "/issues/1328" for 47.23.26.90 at Mon May 06 19:38:16 -0700 2013
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"1328"}
  Current user: vadim (id=5)
  Rendered issues/_action_menu.html.erb (82.8ms)
  Rendered attachments/_links.html.erb (607.6ms)
  Rendered issue_relations/_form.html.erb (203.1ms)
  Rendered issues/_relations.html.erb (218.7ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (3.2ms)
  Rendered issues/_history.html.erb (106.1ms)
  Rendered issues/show.html.erb within layouts/base (1383.6ms)
Completed 500 Internal Server Error in 15510ms

ActionView::Template::Error (compile error
/home/usersvn/redmine.user.com/plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb:2: syntax error, unexpected ':', expecting ')'
 journal.details.where(property: 'attachment').each do |a| 
                                ^
/home/usersvn/redmine.user.com/plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb:2: syntax error, unexpected ')', expecting kEND
 journal.details.where(property: 'attachment').each do |a| 
                                              ^):
    1: <% attachments = Array.new %>
    2: <% journal.details.where(property: 'attachment').each do |a| %>
    3:  <% attachments.push Attachment.find_by_id a.prop_key %>
    4: <% end %>
    5: 
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in`view_issues_history_journal_bottom'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_history.html.erb:19:in`_app_views_issues__history_html_erb___1619062525_1552315616560'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in`_app_views_issues__history_html_erb___1619062525_1552315616560'
  app/views/issues/show.html.erb:122:in `_app_views_issues_show_html_erb___308537064_1552317660420'
  app/controllers/issues_controller.rb:117:in`show'
  app/controllers/issues_controller.rb:114:in `show'

**Comment by serggl** [comment]
Seems like you are using old ruby version. 
Try to pull an update now

**Comment by serggl** [comment]
just pull new version of the plugin

_Sergey A. Glukhov
AnjLab Team_
_http://anjlab.com_
