### ISSUE TITLE
Do not show image, if create new issue

### ISSUE THREAD

**Issue by dbabanov** [anjlab/redmine_inline_note_images_plugin#13]
If create new issue and add picture default way, image do not show, but the file is.
But if i add an image by updating issue, picture is displayed.

Redmine: 2.2.4

**Comment by serggl** [comment]
Can someone else replicate this? since it working fine for me....

_Sergey A. Glukhov
AnjLab Team_
_http://anjlab.com_

**Comment by serggl** [comment]
I think I understand now what you are talking about.
This plugin is only applicable to images attached to issue 'udates'.

If you need to preview images attached to issue details try using lightbox plugin
