### ISSUE TITLE
There is an error when issue has deleted attachment

### ISSUE THREAD

**Issue by atopcu** [anjlab/redmine_inline_note_images_plugin#3]
You can not access to issue after the deleted an attachment from it.

I have removed plugin and I can access it again.

Best Regards,
Adnan

Environment:
  Redmine version                          2.2.0.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.9
  Environment                              production
  Database adapter                         Mysql2

Following is from log:

Started GET "/portal/issues/1870" for XXXXXXXXX at 2013-01-02 15:29:25 +0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"1870"}
  Current user: XXXXXXX (id=XXXX)
  Rendered issues/_action_menu.html.erb (7.2ms)
  Rendered attachments/_links.html.erb (14.3ms)
  Rendered plugins/redmine_issue_checklist/app/views/issues/_checklist.html.erb (3.4ms)
  Rendered plugins/redmine_release_notes/app/views/hooks/release_notes/_view_issues_show_description_bottom.html.erb (1.4ms)
  Rendered issue_relations/_form.html.erb (2.7ms)
  Rendered issues/_relations.html.erb (11.1ms)
  Rendered plugins/redmine_inline_note_images_plugin/app/views/hooks/inline_image_hook/_inline_images_paste.erb (16.1ms)
  Rendered issues/_history.html.erb (20.2ms)
  Rendered issues/show.html.erb within layouts/base (99.9ms)
Completed 500 Internal Server Error in 249ms

ActiveRecord::RecordNotFound (Couldn't find Attachment with id=2990):
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_history.html.erb:19:in`block in _app_views_issues__history_html_erb___2423185781680951933_69967512102320'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in`_app_views_issues__history_html_erb___2423185781680951933_69967512102320'
  app/views/issues/show.html.erb:124:in `_app_views_issues_show_html_erb___2201095056502456313_59177580'
  app/controllers/issues_controller.rb:119:in`block (2 levels) in show'
  app/controllers/issues_controller.rb:116:in `show'

**Comment by serggl** [comment]
This was fixed recently.
Thanks.
