### ISSUE TITLE
Compatible with 2.2.2?

### ISSUE THREAD

**Issue by polarpixel** [anjlab/redmine_inline_note_images_plugin#9]
Seems that the plugin isn't compatible with Redmine 2.2.2?
Can you verify that?

Thanks, Peter.

**Comment by logical-and** [comment]
Why not? =)

**Comment by polarpixel** [comment]
There was a error after installing and restarting Redmine.
I deleted the plugin because it's not so important for me.
Just wanted to ask. Thanks!

**Comment by serggl** [comment]
I think this was an issue with ruby 1.9.3 hash syntax. Closing this
